### ISSUE TITLE
Error while running PetriSpec

### ISSUE THREAD

**Issue by aslesarenko** [iandebeer/ergo-castanet#1]
Tried to run sbt test. Got the following message
```
org.ergoplatform.client.PetriSpec:
==> X org.ergoplatform.client.PetriSpec.build petri net  0.239s java.io.FileNotFoundException: /Users/ian/dev/castanet/modules/core/src/test/resource/petrinet1.dot (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:293)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:184)
    at java.io.PrintWriter.<init>(PrintWriter.java:309)
    at ee.mn8.castanet.PetriPrinter.writeTextToFile(PetriPrinter.scala:53)
    at ee.mn8.castanet.PetriPrinter.print(PetriPrinter.scala:41)
    at org.ergoplatform.client.PetriSpec.$init$$$anonfun$1(PetriSpec.scala:107)
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	org.ergoplatform.client.PetriSpec
[error] (client / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by iandebeer** [comment]
I have fixed the error. It was due to a file path, in the castenet dependency, that should have relative. The dependency version for castanet is now 0.1.5 and it must re-imported. You can pull the updated sbt from GitHub. Thanks for reporting.

**Comment by iandebeer** [comment]
I plan to continue to work on the implementation of the Heads-or_tails scenario over the weekend.

**Comment by aslesarenko** [comment]
Great, will try. 
What is your id in Ergo Discord?

**Comment by iandebeer** [comment]
id: iandebeer

**Comment by aslesarenko** [comment]
and four digit tag?

**Comment by iandebeer** [comment]
#7827
